apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dochaus-workspace
  namespace: poc-doc-haus
  labels:
    app: dochaus
    autopoc.io/project: doc-haus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
