apiVersion: v1
kind: Service
metadata:
  name: dochaus
  namespace: poc-doc-haus
  labels:
    app: dochaus
    autopoc.io/project: doc-haus
spec:
  type: ClusterIP
  selector:
    app: dochaus
  ports:
    - port: 5173
      targetPort: 5173
      name: web
    - port: 4096
      targetPort: 4096
      name: engine
    - port: 4500
      targetPort: 4500
      name: ingest
